### ISSUE TITLE
Step 3: Add a footer containing a link to your teams GitHub repo

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#26]
**__Task Description__**
Add a footer containing a link to our team's GitHub repo.
Steps:

- [x] Create a branch under your name based on the development branch
- [x] Go to the HTML file (landing page and game page)
- [x] Add to the footer

```
<footer><span> &lt;/&gt; with </span>❤️</i><span> by </span>
<span>
<a href="https://github.com/goodman2814" target="_blank">Alex Papparotto</a>,<a href="https://github.com/nazgul7d" target="_blank">Nazgul.</a>,<a href="https://github.com/PaulaR-05" target="_blank"> Gabriela</a>,<a href="https://github.com/MoriahSWalker" target="_blank">Moriah</a>,<a href="https://github.com/Foughty" target="_blank"> John</a>
</span>
<hr>
<span> © 2023 </span><span>Inspired by <a href="https://www.chingu.io" target="_blank">Chingu</a>. Built for Voyage 44. | <a href="https://github.com/chingu-voyages/v44-tier1-team-05" target="_blank">View Source</a> | <a href="https://github.com/chingu-voyages/v44-tier1-team-05/" target="_blank">Learn More</a></span> | <a href="#" id="developersPage">Meet Team 05</a></footer>

```
- [ ] Create a PR(pull request) and wait for the approval

**__Technical Considerations__**
No technical considerations

**__Additional Considerations__**
-
