### ISSUE TITLE
Create a 10x10 grid the game is played on

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#30]
**__Task Description__**
User can see the game window with these components
- [ ]  A 10x10 grid the game is played on
- [ ]  When the dice are rolled the user will be able to click on squares to mark their array.
- [ ]  When a square is clicked it's color will change from the color used for unoccupied squares to the color designation for occupied squares.
- [ ]  If the total number of squares marked on the grid don't match the numbers on the dice an error message must be issued and the user should be given the option to re-mark the grid to match the dice.

**__Technical Considerations__**
Javascript

**__Additional Considerations__**
links to external resources: (https://codepen.io/matteobruni/pen/zYqavva)
