### ISSUE TITLE
Add a button in the game control panel

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#31]
**__Task Description__**
Users can see a button in the game control panel to:
- [ ]  start a new game
- [ ]  update the Leaderboard
- [ ]  clear the grid
- [ ]  start a new game.

**__Technical Considerations__**
Include any technical considerations including architecture (e.g. API), required libraries, etc.

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
