### ISSUE TITLE
Step 4: User can see the game window with these components

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#38]
**__Task Description__**
Functionality
Users can see the game window with these components:
- [x] Leaderboard showing the number of games the current player has won and lost
- [x] Game controls
- [x] A 10x10 grid the game is played on
- [x] Dice area(for displaying the dice numbers)

**__Technical Considerations__**
HTML, Javascript

**__Additional Considerations__**
Grid: https://www.youtube.com/watch?v=23AGsRkghjo
