### ISSUE TITLE
Step 5: Create a Leaderboard panel on HTML Game page

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#39]
**__Task Description__**
User can see the leaderboard area with these components:

- [x] User can see the display of the total number of wins and losses for each;
- [x]  User can see the tally of wins for each of the three ways the game can end;
- [x]  User can see the tally of losses for each of the three ways the game can end
