### ISSUE TITLE
Add a button in the game control panel to start a new game

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#42]
**__Task Description__**
User can see a button in the game control panel to start a new game, which:

- [ ]  updates the Leaderboard
- [ ]  clears the grid,
- [ ]  starts a new game.

**__Technical Considerations__**
HTML, Javascript

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.
