### ISSUE TITLE
Write a function that display grid interactions

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#49]
**__Task Description__**
This function should display:

- [x]  When the dice are rolled the user will be able to click on squares to mark their array.
- [x]  When a square is clicked its color will change from the color used for unoccupied squares to the color designation for occupied squares.
- [x]  If the total number of squares marked on the grid doesn't match the numbers on the dice an error message must be issued and the user should be given the option to re-mark the grid to match the dice.

**__Technical Considerations__**
Javascript

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by PaulaR-05** [comment]
Naz, i found this link that maybe we could get some logic from it 
https://www.geeksforgeeks.org/html-scientific-calculator/

**Comment by nazgul7d** [comment]
> Naz, i found this link that maybe we could get some logic from it https://www.geeksforgeeks.org/html-scientific-calculator/

Thank you so much, I'll have a look
