### ISSUE TITLE
In case we meet the MVP, we will add more features that we voted on SPRINT 2

### ISSUE THREAD

**Issue by PaulaR-05** [chingu-voyages/v44-tier1-team-05#51]
**__Task Description__**
In case we meet the MVP, we will add some more features that we voted on SPRINT 2 :)

Voted:

- [x] Play a sound to simulate the rolling dice

- [x] Animate the rolling of the dice

- [x] Support dark/light mode

**Comment by PaulaR-05** [comment]
We almost have it done hahaha It's missing the dark/light mode 
If we finish the MVP we can add it
